# all configuration should really be in .bash_profile_includes
OS=`uname -s`
source ~/.bash_profile_includes/${OS}/paths.sh

alias my_projects='cd ~/projects/hearsay-learning-python'

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
